config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'home#index'

  get "home/items" => "home#items"

  namespace :admin do
    resources :products
    resources :users do
      member do
        post :to_admin
        post :to_normal
      end
    end
  end

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :product, dependent: :destroy
  mount_uploader :image, ImageUploader
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :photo
  accepts_nested_attributes_for :photo
end

app/models/settings.rb
class Settings < Settingslogic
  source "#{Rails.root}/config/application.yml"
  namespace Rails.env
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  extend OmniauthCallbacks

  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable,
    :omniauthable, :omniauth_providers => [:facebook]

  def admin?
    is_admin
  end

  def to_admin
    self.update_columns(is_admin: true)
  end

  def to_normal
    self.update_columns(is_admin: false)
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.name = auth.info.name
      p auth
      user.password = Devise.friendly_token[0,20]
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController

  before_action :authenticate_user!
  before_action :admin_required
  layout 'admin/application'

  def index
    @products = Product.all
    # @photos = @product.photo.all
  end

  def new
    @product = Product.new
    @photo = @product.photo.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      if params[:photos] != nil
        params[:photos]['image'].each do |a|
          @photo = @product.photo.create(:image => a)
        end
      end
      redirect_to admin_products_path
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
    if @product.photo.present?
      @photo = @product.photo
    else
      @photo = @product.photo.build
    end
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to admin_products_path
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    Photo.where(:product => params[:id]).delete_all
    @product.destroy
    redirect_to admin_products_path
  end
  private

  def product_params
    params.require(:product).permit(:title, :format, :description, :quantity, :price, :other, photo_attributes: [:image, :id])
  end
  def admin_required
    if !current_user.admin?
      redirect_to "/"
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  before_action :authenticate_user!
  before_action :admin_required
  layout 'admin/application'


  def index
    @users = User.all
  end

  def to_admin
    @user = User.find(params[:id])
    @user.to_admin

    redirect_to admin_users_path
  end

  def to_normal
    @user = User.find(params[:id])
    @user.to_normal

    redirect_to admin_users_path
  end
  private
  def admin_required
    if !current_user.admin?
      redirect_to "/"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def failure
    super
  end

  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      #略過認證信
      # @user.skip_confirmation!
      sign_in_and_redirect @user , :event => :authentication
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to root_url
    end
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  layout false
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/products/edit.html.erb
<%= simple_form_for [:admin, @product] do |f| %>
  <div class="group">
    <%= f.input :title %>
  </div>
  <% if @product.photo.present? %>
    <% @product.photo.each do |p| %>
      <li class="menu" style="list-style-type:none;float: left">
        <%= image_tag p.image.thumb.url %><br>
        <%= link_to("Delete", admin_product_path(@photo), method: :delete, data:{confirm: "Are you sure?"}, class: "btn btn-xs btn-danger") %>
      </li>
    <% end %>
  <% end %>
  <div class="form-group">
    <%= f.simple_fields_for :photo do |c| %>
      <%= c.input :image , as: :file %>
    <% end %>
  </div>
  <div class="group">
    <%= f.input :description %>
  </div>
  <div class="group">
    <%= f.input :quantity %>
  </div>
  <div class="group">
    <%= f.input :price %>
  </div>
</div>
<%= f.submit "Submit", data: { disable_with: "Submitting..." } %>
<% end %>

app/views/admin/products/index.html.erb
<h2> Product List </h2>
<div class="pull-right" style="padding-bottom: 20px;">
  <%= link_to("前台首頁", root_path, class: "btn btn-primary btn-sm") %>
  <%= link_to("新增產品", new_admin_product_path, class: "btn btn-primary btn-sm") %>
</div>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>#</th>
      <th width="220">Product Pic</th>
      <th>Name</th>
      <th>Price</th>
      <th width="100"> Options</th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td>
          <%= product.id %>
        </td>
        <td>
          <%= link_to admin_product_path(product) do %>
            <% if product.photo.present? %>
              <% product.photo.each do |p| %>
                <%= image_tag p.image.thumb.url %><br>
              <% end %>
            <% else %>
              <%= image_tag("http://placehold.it/100x100&text=No Pic", class: "thumbnail") %>
            <% end %>
          <% end %>
        </td>
        <td>
          <%= product.title %>
        </td>
        <td>
          <%= product.price %>
        </td>
        <td>
          <%= link_to("Edit", edit_admin_product_path(product)) %>
          <%= link_to(t('.Delete'), admin_product_path(product), method: :delete, data:{confirm: "Are you sure?"}, class: "btn btn-xs btn-danger") %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/products/new.html.erb
<div class="col-xs-8 col-xs-offset-2">
  <h2> 新增產品 </h2>
  <%= simple_form_for [:admin, @product] do |f| %>
    <div class="group">
      <%= f.input :title %>
    </div>
    <div class="form-group">
      <%= f.simple_fields_for :photo do |c| %>
        <%#= f.input :image, as: :file %>
        <%= f.label :image %><br>
        <%= f.file_field :image, :multiple => true, name: "photos[image][]" %>
      <% end %>
    </div>
    <div class="group">
      <%= f.input :description %>
    </div>
    <div class="group">
      <%= f.input :quantity %>
    </div>
    <div class="group">
      <%= f.input :price %>
    </div>
    <%= f.submit "Submit", data: { disable_with: "Submitting..." } %>
  <% end %>
</div>

app/views/admin/users/index.html.erb
<h2>使用者列表</h2>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>#</th>
      <th>Email</th>
      <th>權限</th>
      <th>功能</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td>
          <%= user.id %>
        </td>
        <td>
          <%= user.email %>
        </td>
        <td>
          <% if user.admin? %>
            管理者
          <% else %>
            一般使用者
          <% end %>
        </td>
        <td>
          <% if user.admin? %>
            <%= link_to("轉為一般使用者", to_normal_admin_user_path(user), method: :post, class: "btn btn-info") %>
          <% else %>
            <%= link_to("轉為管理者", to_admin_admin_user_path(user), method: :post, class: "btn btn-primary") %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/compent/_nav.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role=navigation>
  <div class="container">
    <div class="navbar-header">
      <div class="col-xs-12">
        <div class="col-xs-2">
          <!-- <a href="#">
            <span class="glyphicon glyphicon-menu-hamburger" aria-hidden="true">
            </span>
          </a> -->
          <button class="fa fa-bars easy-sidebar-toggle">
          </button>
        </div>
        <div class=col-xs-5>
          <%= link_to(image_tag("logo.png", class: 'logo'), root_path) %>
        </div>
        <div class="col-xs-3" style="list-style-type:none">
          <% if !current_user %>
            <%= link_to  new_user_session_path do %>
              <i class="fa fa-user"></i>
            <% end %>
            <a class="fa fa-shopping-cart" href="#"></a>
          <% else %>
            <li class="dropdown">
              <a herf="#" class="dropdown-toggle" data-toggle="dropdown">
                <i class="fa fa-user"></i>
                <a class="fa fa-shopping-cart" href="#"></a>
              </a>
              <ul class="dropdown-menu">
                <li> <%= link_to("登出", destroy_user_session_path, method: :delete) %> </li>
                <li>
                  <% if current_user.is_admin = true %>
                    <%= link_to("後台管理", admin_products_path) %>
                    <%= link_to("使用者管理", admin_users_path) %>
                  <% end %>
                </li>
              </ul>
            </li>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>
<nav class="navbar navbar-inverse easy-sidebar">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href='#'><span class="fa fa-home" >Home</span></a>
    </div>
  </div>
  <div class="sreach">
    <%= form_tag root_path, method: "get" do %><%= text_field_tag :name %>
      <%= submit_tag '收尋'%>
    <% end %>
  </div>
  <h4>商品分類</h4>
  <ul class="nav navbar-nav">
    <li><a href="#">人氣商品</a></li>
    <li><a href="#">新品入荷</a></li>
  </ul>
</div>
<!-- /.container-fluid -->
</nav>

app/views/home/items.html.erb
<div class="col-xs-12 item-title">
  <div class="title">
    <strong class="title-left-text">人氣商品</strong>
    <span class="title-right-text">共92結果</span>
  </div>
</div>
<div class="col-xs-12 sort">
  <%= form_tag home_items_path, method: "get", class:"sort-select" do %>
    <% select_tag options_for_select([['上架日期', '上架日期'], ['熱銷商品', '熱銷商品'], ['瀏覽人次', '瀏覽人次'], ['價格由低至高', '價格由低至高'], ['價格由高至低', '價格由高至低']], params[:city]) %>
  <% end %>
  <span class="sort-text">排序：</span>
</div>
<div class="col-xs-12 col-item">
  <div class="col-xs-6 commodity-lattice">
    <ul class="Kg_ProductList clearfix">
      <li>
        <div class="se_ProductStyle">
          <a href="#" title="帝王蟹龍蝦豪華組">
            <img class="commodity-image" src="http://rs.sushigogo.com.tw/website/uploads_product/website_4/P0000400000023_2_2414.png" title="帝王蟹龍蝦豪華組" alt="帝王蟹龍蝦豪華組">
          </a>
          <h2 class="se_Product_Name"><a class="se_Product_soldout" href="#" title="帝王蟹龍蝦豪華組">帝王蟹龍蝦豪華組</a></h2>
        </div>
      </li>
    </ul>
    <ul class="product-detail">
      <h4 class="product-detail-text">蟹 1kg±10％ / 隻；蝦 500g / 隻</h4>
    </ul>
    <ul class="se_Product_price clearfix">
      <li class="se_Product_price01"><span>$</span>1399</li>
      <li class="se_Product_price02">$1555</li>
    </ul>
    <div class="col-xs-8 se_Product_btn">
      <a class="fa fa-cart-plus" href="#"></a>
      <a class="fa fa-heart-o" href="#">
      </a>
    </div>
  </div>
  <div class="col-xs-6 commodity-lattice">
    <ul class="Kg_ProductList clearfix">
      <li>
        <div class="se_ProductStyle">
          <a href="#" title="帝王蟹龍蝦豪華組">
            <span class="se_Product_soldout" id="soldout_1229" style="display: none;">
            </span>
            <img class="commodity-image" src="http://rs.sushigogo.com.tw/website/uploads_product/website_4/P0000400000023_2_2414.png" title="帝王蟹龍蝦豪華組" alt="帝王蟹龍蝦豪華組">
          </a>
          <h2 class="se_Product_Name"><a class="se_Product_soldout" href="#" title="帝王蟹龍蝦豪華組">帝王蟹龍蝦豪華組</a></h2>
        </div>
      </li>
    </ul>
    <ul class="product-detail">
      <h4 class="product-detail-text">蟹 1kg±10％ / 隻；蝦 500g / 隻</h4>
    </ul>
    <ul class="se_Product_price clearfix">
      <li class="se_Product_price01"><span>$</span>1399</li>
      <li class="se_Product_price02">$1555</li>
    </ul>
    <div class="col-xs-8 se_Product_btn">
      <a class="fa fa-cart-plus" href="#"></a>
      <a class="fa fa-heart-o" href="#">
      </a>
    </div>
  </div>
</div>

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html class="easy-sidebar-active">
  <head>
    <title>ShopGogo</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
  </head>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="easy-sidebar-active">
  <head>
    <title>ShopGogo</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
  </head>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="col-xs-12 need-col-12">
    <%= render "compent/nav" %>
  </div>
  <%= yield %>
</body>
</html>